### PR TITLE
Add abbreviations to create unicode ops

### LINKED ISSUE #8: Feature request: automatically replace texas ops with unicode equivalents
This ticket is inspired by [reddit comments](https://www.reddit.com/r/perl/duplicates/6v8eop/201734_going/).

Example: you type ``<=``, it should automatically replaces it with ``≤``. Obviously, make it possible to turn that feature off, but perhaps consider having it enabled by default.

List of non-texas ops: https://docs.perl6.org/language/unicode_texas

Sister tickets:
* [atom-language-perl6](https://github.com/perl6/atom-language-perl6/issues/72)
* [perl6-mode](https://github.com/perl6/perl6-mode/issues/14)

### PR DESCRIPTION
**Pull request by Tyil**
Fixes #8

### CODE REVIEW

**Comment by Tyil** [comment]
Two weeks with no response, I'm forking this into @scriptkitties and will apply patches there. If this project stays dead and my patches work well enough, I'll update the link to the vim-perl6 plugin on docs.perl6 as well.

**Comment by petdance** [comment]
I'd like to suggest that "we haven't looked at it in 15 days" is not the same thing as "dead".

**Comment by hoelzro** [comment]
@Tyil Sorry for the delay - I tend to work on OSS projects on a six-week cycle, and I'm playing catch-up right now.  This project *has* stagnated some, though - would you be up for helping to maintain it?

**Comment by Tyil** [comment]
@petdance Some PRs have taken literal months before being looked at, that doesn't say the project is very much alive either.

@hoelzro I am up to help to maintain it, I'd just maintain it under a different namespace anyway.

**Comment by hoelzro** [comment]
@Tyil so you would maintain it under a different account? (eg. @scriptkitties)?

**Comment by Tyil** [comment]
I don't mind where it's being maintained, so long as I can add code easily and get feedback in a reasonable timespan. I'm currently also working on a `templates` branch, which has gotten some feedback already.

**Comment by hoelzro** [comment]
Well, we could always give you push access to this repo =)  My opinion regarding the purpose of this repo is that it's syntax, ftplugin, and indent only - I think things like templates would be better suited as a separate plugin.  That way people can choose which template plugin they want to use and not have it conflict with vim-perl6!

**Comment by Tyil** [comment]
That sounds valid. Not everyone wants templates either, though both features (templates and unicode abbreviations) are disabled by default already as well, since I don't know if they work correctly for everyone in every circumstance.

If I were to get push access here I'd gladly take care of PRs, review them as needed and merge them if they fix something. I'd gladly assist in a collaborated effort on this repo, as I think it's better to work together to get the best result possible.

**Comment by hoelzro** [comment]
@Tyil This looks good - would you mind putting the `iabbrev` statements in an `if` block, as suggested in #8?

Another thing to consider with the templates is if Bram will want such a facility in upstream Vim - part of our responsibility is to push updated runtime files to Vim itself.

**Comment by Tyil** [comment]
It already has that in my fork, but it seems Github can't deal with my fork now being based off of scriptkitties/vim-perl6, which is based off of this repository. It says `unknown repository` at the PR as well, and I can't seem to update that.

**Comment by Tyil** [comment]
I made a new PR to rectify this, and to show all commits on the branch correctly: #10

**Pull request closed without merging**
